# mybatis 的配置
mybatis:
  config-location: classpath:./xml/mybatis-config.xml
  mapper-locations: classpath:./xml/mybatis/*.xml

# 日志
logging:
  level:
    com.p6e.germ.oauth2.infrastructure.repository.mapper: debug

spring:
  application:
    name: P6E_GERM_OAUTH2
  datasource:
    url: jdbc:mysql://321312:3306/p6e?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Root1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 9
    host: 3123123
    port: 6379
    password: 31231
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0


server:
  port: 80

p6e:
  oauth2:
    qq:
      client-id: 101701115
      client-secret: 165716bf22444998e0394d0e244e13d7
      redirect-uri: http://www.zhimamimi.com/login/qq/callback

