# 端口配置
server:
  port: ${my.server.port}

# spring 配置
spring:
  # 名称配置
  application:
    name: P6E_GERM_OAUTH2
  # 数据源配置
  datasource:
    url: ${my.db.url}
    username: ${my.db.username}
    password: ${my.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: ${my.cache.redis.source_1.database}
    host: ${my.cache.redis.source_1.host}
    port: ${my.cache.redis.source_1.port}
    password: ${my.cache.redis.source_1.password}
    timeout: ${my.cache.redis.source_1.timeout}
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

# p6e 的配置
p6e:
  oauth2:
    qr-code:
      url: 'https://baidu.com/auth?code='
    qq:
      enable: true
      client-id: ${my.oauth2.qq.client.id}
      client-secret: ${my.oauth2.qq.client.secret}
      redirect-uri: ${my.oauth2.qq.redirect}
    we-chat:
      enable: false
      client-id: ${my.oauth2.we_chat.client.id}
      client-secret: ${my.oauth2.we_chat.client.secret}
      redirect-uri: ${my.oauth2.we_chat.redirect}
  cache:
    redis:
      timeout: ${my.cache.redis.source_1.timeout}
      source:
        A:
          host: ${my.cache.redis.source_1.host}
          port: ${my.cache.redis.source_1.port}
          database: ${my.cache.redis.source_1.database}
          password: ${my.cache.redis.source_1.password}




# mybatis 的配置
mybatis:
  config-location: classpath:./xml/mybatis-config.xml
  mapper-locations: classpath:./xml/mybatis/*.xml

# 日志
logging:
  level:
    com.p6e.germ.oauth2.infrastructure.repository.mapper: debug





