# 服务器启动的端口
server:
  port: 9000

# mybatis 的配置
mybatis:
  config-location: classpath:./xml/mybatis-config.xml
  mapper-locations: classpath:./xml/mybatis/*.xml

# 日志
logging:
  level:
    com.p6e.germ.oauth.mapper: debug
    com.p6e.germ.security.mapper: debug

spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  application:
    name: P6E_GERM_OAUTH2
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2?autoReconnect=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: Root1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 11
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
p6e:
  security:
    token: 1234567890
    group:
      url: http://127.0.0.1:${server.port}/security/group/token
    jurisdiction:
      url: http://127.0.0.1:${server.port}/security/jurisdiction/token
